# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-03 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='urls',
            new_name='url',
        ),
    ]
